// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXIRKWV9G4GL2lbUIHlV41ezoZnc_fh0',
    appId: '1:836556442493:web:498a616ee9e3badbd7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    authDomain: 'manual-test-f0181.firebaseapp.com',
    storageBucket: 'manual-test-f0181.appspot.com',
    measurementId: 'G-0BCSBVNY68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeW-qR7M_L9MOhO6hzVAj9ynJo6A2mSy0',
    appId: '1:836556442493:android:5b33d4cdfa190334d7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    storageBucket: 'manual-test-f0181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKK4C_lMnUY691PIIx13PnTs4OH-B1Gc',
    appId: '1:836556442493:ios:2ce326242e1f2159d7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    storageBucket: 'manual-test-f0181.appspot.com',
    iosClientId: '836556442493-lqrl82sr923884k24hg2qoapaqrpn5it.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOauthSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKK4C_lMnUY691PIIx13PnTs4OH-B1Gc',
    appId: '1:836556442493:ios:2ce326242e1f2159d7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    storageBucket: 'manual-test-f0181.appspot.com',
    iosClientId: '836556442493-lqrl82sr923884k24hg2qoapaqrpn5it.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOauthSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXIRKWV9G4GL2lbUIHlV41ezoZnc_fh0',
    appId: '1:836556442493:web:7b9b651d3c5f5005d7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    authDomain: 'manual-test-f0181.firebaseapp.com',
    storageBucket: 'manual-test-f0181.appspot.com',
    measurementId: 'G-8BPSLFKDBL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBEXIRKWV9G4GL2lbUIHlV41ezoZnc_fh0',
    appId: '1:836556442493:web:c3e2ded61bccef37d7da14',
    messagingSenderId: '836556442493',
    projectId: 'manual-test-f0181',
    authDomain: 'manual-test-f0181.firebaseapp.com',
    storageBucket: 'manual-test-f0181.appspot.com',
    measurementId: 'G-47JQQ234WJ',
  );
}
